### ISSUE TITLE
update for new lme4 release

### ISSUE THREAD

**Issue by bbolker** [KechrisLab/HeritSeq#1]
lme4 has changed the default optimizer, which leads to some testing errors on Windows - I suspect they can all be fixed by slightly weakening tolerances used for tests ...

**Comment by wjshi** [comment]
We adjusted the tolerance from 5e-5 to 1e-4 in lme4::glmer.nb in the HeritSeq package. The updated version HeritSeq_1.0.1 has been submitted to CRAN.

**Comment by bbolker** [comment]
thank you!
